# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: x/custommint/types/query.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'x/custommint/types/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ex/custommint/types/query.proto\x12\x12x.custommint.types\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x1cgoogle/api/annotations.proto\"\x19\n\x17QueryTotalMintedRequest\"E\n\x18QueryTotalMintedResponse\x12)\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.Coin\"\x19\n\x17QueryTotalBurnedRequest\"E\n\x18QueryTotalBurnedResponse\x12)\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.Coin\"\x14\n\x12QueryParamsRequest\"\xce\x01\n\x13QueryParamsResponse\x12\x16\n\x0e\x62urn_threshold\x18\x01 \x01(\t\x12\x12\n\nburn_ratio\x18\x02 \x01(\t\x12\x17\n\x0f\x62locks_per_year\x18\x03 \x01(\x03\x12\x1c\n\x14\x66irst_year_inflation\x18\x04 \x01(\t\x12\x1d\n\x15second_year_inflation\x18\x05 \x01(\t\x12\x1c\n\x14other_year_inflation\x18\x06 \x01(\t\x12\x17\n\x0fuusdt_authority\x18\x07 \x01(\t\"\x17\n\x15QueryInflationRequest\"+\n\x16QueryInflationResponse\x12\x11\n\tinflation\x18\x01 \x01(\t2\xb4\x04\n\x05Query\x12\x8f\x01\n\x0bTotalMinted\x12+.x.custommint.types.QueryTotalMintedRequest\x1a,.x.custommint.types.QueryTotalMintedResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/paxi/custommint/total_minted\x12\x8f\x01\n\x0bTotalBurned\x12+.x.custommint.types.QueryTotalBurnedRequest\x1a,.x.custommint.types.QueryTotalBurnedResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/paxi/custommint/total_burned\x12z\n\x06Params\x12&.x.custommint.types.QueryParamsRequest\x1a\'.x.custommint.types.QueryParamsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/paxi/custommint/params\x12\x8a\x01\n\tInflation\x12).x.custommint.types.QueryInflationRequest\x1a*.x.custommint.types.QueryInflationResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/cosmos/mint/v1beta1/inflationB4Z2github.com/paxi-web3/paxi/x/custommint/types;typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'x.custommint.types.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/paxi-web3/paxi/x/custommint/types;types'
  _globals['_QUERY'].methods_by_name['TotalMinted']._loaded_options = None
  _globals['_QUERY'].methods_by_name['TotalMinted']._serialized_options = b'\202\323\344\223\002\037\022\035/paxi/custommint/total_minted'
  _globals['_QUERY'].methods_by_name['TotalBurned']._loaded_options = None
  _globals['_QUERY'].methods_by_name['TotalBurned']._serialized_options = b'\202\323\344\223\002\037\022\035/paxi/custommint/total_burned'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\031\022\027/paxi/custommint/params'
  _globals['_QUERY'].methods_by_name['Inflation']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Inflation']._serialized_options = b'\202\323\344\223\002 \022\036/cosmos/mint/v1beta1/inflation'
  _globals['_QUERYTOTALMINTEDREQUEST']._serialized_start=116
  _globals['_QUERYTOTALMINTEDREQUEST']._serialized_end=141
  _globals['_QUERYTOTALMINTEDRESPONSE']._serialized_start=143
  _globals['_QUERYTOTALMINTEDRESPONSE']._serialized_end=212
  _globals['_QUERYTOTALBURNEDREQUEST']._serialized_start=214
  _globals['_QUERYTOTALBURNEDREQUEST']._serialized_end=239
  _globals['_QUERYTOTALBURNEDRESPONSE']._serialized_start=241
  _globals['_QUERYTOTALBURNEDRESPONSE']._serialized_end=310
  _globals['_QUERYPARAMSREQUEST']._serialized_start=312
  _globals['_QUERYPARAMSREQUEST']._serialized_end=332
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=335
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=541
  _globals['_QUERYINFLATIONREQUEST']._serialized_start=543
  _globals['_QUERYINFLATIONREQUEST']._serialized_end=566
  _globals['_QUERYINFLATIONRESPONSE']._serialized_start=568
  _globals['_QUERYINFLATIONRESPONSE']._serialized_end=611
  _globals['_QUERY']._serialized_start=614
  _globals['_QUERY']._serialized_end=1178
# @@protoc_insertion_point(module_scope)
