version: '3.8'

services:
  paxi-node:
    container_name: paxi-node-1
    image: paxi-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/root/.paxid      
    ports:
      - "26656:26656"   # p2p
      - "26657:26657"   # RPC
      - "9090:9090"     # gRPC
      - "1317:1317"     # REST
    restart: unless-stopped
    environment:
      - PAXID_MONIKER=my-validator
    command: ["./paxid", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/health"]
      interval: 30s
      timeout: 10s
      retries: 5
