# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: x/customwasm/types/tx.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'x/customwasm/types/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bx/customwasm/types/tx.proto\x12\x12x.customwasm.types\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\"y\n\x0bParamsInput\x12\x1b\n\x13store_code_base_gas\x18\x01 \x01(\x04\x12\x1d\n\x15store_code_multiplier\x18\x02 \x01(\x04\x12\x15\n\rinst_base_gas\x18\x03 \x01(\x04\x12\x17\n\x0finst_multiplier\x18\x04 \x01(\x04\"k\n\x0fMsgUpdateParams\x12\x11\n\tauthority\x18\x01 \x01(\t\x12\x35\n\x06params\x18\x02 \x01(\x0b\x32\x1f.x.customwasm.types.ParamsInputB\x04\xc8\xde\x1f\x00:\x0e\x82\xe7\xb0*\tauthority\"\x19\n\x17MsgUpdateParamsResponse2n\n\x03Msg\x12`\n\x0cUpdateParams\x12#.x.customwasm.types.MsgUpdateParams\x1a+.x.customwasm.types.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01\x42.Z,github.com/paxi-web3/paxi/x/customwasm/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'x.customwasm.types.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/paxi-web3/paxi/x/customwasm/types'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_MSGUPDATEPARAMS']._loaded_options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_PARAMSINPUT']._serialized_start=98
  _globals['_PARAMSINPUT']._serialized_end=219
  _globals['_MSGUPDATEPARAMS']._serialized_start=221
  _globals['_MSGUPDATEPARAMS']._serialized_end=328
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=330
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=355
  _globals['_MSG']._serialized_start=357
  _globals['_MSG']._serialized_end=467
# @@protoc_insertion_point(module_scope)
