# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from x.swap.types import query_pb2 as x_dot_swap_dot_types_dot_query__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in x/swap/types/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/x.swap.types.Query/Params',
                request_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.Position = channel.unary_unary(
                '/x.swap.types.Query/Position',
                request_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryPositionRequest.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryPositionResponse.FromString,
                _registered_method=True)
        self.Pool = channel.unary_unary(
                '/x.swap.types.Query/Pool',
                request_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryPoolRequest.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryPoolResponse.FromString,
                _registered_method=True)
        self.AllPools = channel.unary_unary(
                '/x.swap.types.Query/AllPools',
                request_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryAllPoolsRequest.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryAllPoolsResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Params(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Position(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllPools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'Position': grpc.unary_unary_rpc_method_handler(
                    servicer.Position,
                    request_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryPositionRequest.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryPositionResponse.SerializeToString,
            ),
            'Pool': grpc.unary_unary_rpc_method_handler(
                    servicer.Pool,
                    request_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryPoolRequest.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryPoolResponse.SerializeToString,
            ),
            'AllPools': grpc.unary_unary_rpc_method_handler(
                    servicer.AllPools,
                    request_deserializer=x_dot_swap_dot_types_dot_query__pb2.QueryAllPoolsRequest.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_query__pb2.QueryAllPoolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'x.swap.types.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('x.swap.types.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Query/Params',
            x_dot_swap_dot_types_dot_query__pb2.QueryParamsRequest.SerializeToString,
            x_dot_swap_dot_types_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Position(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Query/Position',
            x_dot_swap_dot_types_dot_query__pb2.QueryPositionRequest.SerializeToString,
            x_dot_swap_dot_types_dot_query__pb2.QueryPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Query/Pool',
            x_dot_swap_dot_types_dot_query__pb2.QueryPoolRequest.SerializeToString,
            x_dot_swap_dot_types_dot_query__pb2.QueryPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllPools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Query/AllPools',
            x_dot_swap_dot_types_dot_query__pb2.QueryAllPoolsRequest.SerializeToString,
            x_dot_swap_dot_types_dot_query__pb2.QueryAllPoolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
