# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from x.swap.types import tx_pb2 as x_dot_swap_dot_types_dot_tx__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in x/swap/types/tx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MsgStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParams = channel.unary_unary(
                '/x.swap.types.Msg/UpdateParams',
                request_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
                _registered_method=True)
        self.ProvideLiquidity = channel.unary_unary(
                '/x.swap.types.Msg/ProvideLiquidity',
                request_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgProvideLiquidity.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgProvideLiquidityResponse.FromString,
                _registered_method=True)
        self.WithdrawLiquidity = channel.unary_unary(
                '/x.swap.types.Msg/WithdrawLiquidity',
                request_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgWithdrawLiquidity.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgWithdrawLiquidityResponse.FromString,
                _registered_method=True)
        self.Swap = channel.unary_unary(
                '/x.swap.types.Msg/Swap',
                request_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgSwap.SerializeToString,
                response_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgSwapResponse.FromString,
                _registered_method=True)


class MsgServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideLiquidity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithdrawLiquidity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgUpdateParams.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
            'ProvideLiquidity': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideLiquidity,
                    request_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgProvideLiquidity.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgProvideLiquidityResponse.SerializeToString,
            ),
            'WithdrawLiquidity': grpc.unary_unary_rpc_method_handler(
                    servicer.WithdrawLiquidity,
                    request_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgWithdrawLiquidity.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgWithdrawLiquidityResponse.SerializeToString,
            ),
            'Swap': grpc.unary_unary_rpc_method_handler(
                    servicer.Swap,
                    request_deserializer=x_dot_swap_dot_types_dot_tx__pb2.MsgSwap.FromString,
                    response_serializer=x_dot_swap_dot_types_dot_tx__pb2.MsgSwapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'x.swap.types.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('x.swap.types.Msg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Msg/UpdateParams',
            x_dot_swap_dot_types_dot_tx__pb2.MsgUpdateParams.SerializeToString,
            x_dot_swap_dot_types_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideLiquidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Msg/ProvideLiquidity',
            x_dot_swap_dot_types_dot_tx__pb2.MsgProvideLiquidity.SerializeToString,
            x_dot_swap_dot_types_dot_tx__pb2.MsgProvideLiquidityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithdrawLiquidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Msg/WithdrawLiquidity',
            x_dot_swap_dot_types_dot_tx__pb2.MsgWithdrawLiquidity.SerializeToString,
            x_dot_swap_dot_types_dot_tx__pb2.MsgWithdrawLiquidityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Swap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x.swap.types.Msg/Swap',
            x_dot_swap_dot_types_dot_tx__pb2.MsgSwap.SerializeToString,
            x_dot_swap_dot_types_dot_tx__pb2.MsgSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
